$fileManager = thunar
$menu = fuzzel

exec-once = $terminal
exec-once = sunsetr
exec-once = waybar
exec-once = swww-daemon & sleep 0.1 && swww img wallpaper/7mSSR7w.png --transition-type fade --transition-duration 0.4

env = GTK_THEME,adw-gtk3
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, Q, killactive,

# Screenshot a window
bind = , PRINT, exec, hyprshot -m window
# Screenshot a monitor
bind = $shiftMod, PRINT, exec, hyprshot -m output
# Screenshot a region
bind = $mainMod, PRINT, exec, hyprshot -m region
